# Generated by Django 5.0.4 on 2024-04-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRentIhaHistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrentihahistory',
            name='user',
        ),
    ]
