# Generated by Django 5.0.4 on 2024-04-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iha_model', to='iha.model'),
        ),
    ]
