# Generated by Django 5.0.4 on 2024-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0003_alter_brand_id_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
